<?php
class IndexAction extends AuthAction{
	
    protected $token;
    protected $mid;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->token =  session('token');
        if (empty($this->token)) {
            $this->redirect('Auth/login'); die;//未登录
        }
        
        $this->mid = S($this->token);
        if (empty($this->mid)) {
            $this->redirect('Auth/login'); die;//已登陆但登录过期
        }
        S($this->token,$this->mid,86400);
        
        //转专业    中欧选拔    生成转专业pdf   报名
        if (ACTION_NAME == 'changeSpeciality'|| ACTION_NAME == 'collegeSelection'|| ACTION_NAME == 'zzyDownload'|| ACTION_NAME == 'SubSignUp') {
            $data = M('bm_options')->where(array('bm_type'=>array('in',array(1,2))))->field('bm_type,registration_switch')->select();
            list($zzy,$zo) = $data;
            if ((ACTION_NAME == 'changeSpeciality' || ACTION_NAME == 'zzyDownload') && $zzy['registration_switch'] == 2) {
                $this->redirect('Index/index');die;
            }
            if (ACTION_NAME == 'collegeSelection' && $zo['registration_switch'] == 2) {
                $this->redirect('Index/index');die;
            }
            if (ACTION_NAME == 'SubSignUp') {
                $type = I('post.type');
                if (in_array($type,array(1,2))) {
                    if ($type == 1 && $zzy['registration_switch'] == 2) {
                        $this->redirect('Index/index');die;
                    }
                    if ($type == 2 && $zo['registration_switch'] == 2) {
                        $this->redirect('Index/index');die;
                    }
                }
                
            }
        }
    }
    
    //个人页
    public function index()
    {
        try {
            $member_info = $this->memberdb->where(['id'=>$this->mid])->find();
            //select bm_type,registration_switch from ycity_bm_options where bm_type in (1,2,3,5);
            $data = M('bm_options')->where(array('bm_type'=>array('in',array(1,2,3,5))))->field('bm_type,registration_switch')->select();
            
            list($zzy,$zo,$kckb,$gsp) = $data;
            $this->assign('info',$member_info);//成员信息
            $this->assign('zzy',$zzy);//转专业
            $this->assign('zo',$zo);//中欧
            $this->assign('kckb',$kckb);//空乘空保
            $this->assign('moduleName','报名入口');
            /* 高水平是否已报名 select id from ycity_gspydybm where mid= */
            $has = M('Gspydybm')->where(['mid'=>$this->mid])->field('id')->select();

            if (false != $has || ($gsp['registration_switch'] == 1 && $gsp['bm_type'] == 5)){ //已报名的继续展示入口 或者 入口开启状态为开启
                $this->assign('gsp',$gsp);
            }
            $this->display('');
        } catch (\Exception $e) {
            echo C('404HTML');
        }
    }
    public function getInto()
    {
        $type = I('type');
        if (in_array($type,array(1,2))) {
            $info = $this->get_member_info($this->mid);
            if ($info == false) {
                $this->ajaxReturn(['code'=>-1,'msg'=>'仅限本校已经录取的'.date('Y').'级新生才可报名']);
            } else {
                if ($type == 1) $url = U('Index/changeSpeciality');
                if ($type == 2) $url = U('Index/collegeSelection');
                $this->ajaxReturn(['code'=>1,'msg'=>'','url'=>$url]);
            }
        }
       exit();
    }
    //修改手机号
    public function modifyPhone()
    {
        if (IS_POST) {
            $phone = I('post.phone');
            $sms_code = I('post.sms_code');
            $cabinUrl = urlencode(I('post.redirect_uri'));
            $msg = '缺少必填参数';
            if (!empty($phone) && !empty($sms_code)) {
                $msg = '短信验证码错误';
                if ($this->_varifyActivation($phone,'mobile',$sms_code)) {
                    $save = ['phone'=>$phone];
                    //修改成功后需要重新登录
                    $Yphone = $this->memberdb->where(['id'=>$this->mid])->getField('phone');
                    if ($Yphone != $save['phone']) {
                        if ($this->memberdb->where(['id'=>$this->mid])->setField($save)) {
                            $code = 1;
                            $msg = '修改成功，请重新登录';

                            $url = C('S_IP').'Member/Login/logoutApi';//乘务退出登录的接口地址
                            $data = array('token'=> $this->token);

                            $re1 = json_decode($this->httpPsot($url,$data),true);
                            if ($re1['code'] == 1) {
                                session('user_name',null);
                                session('token',null);
                                S($this->token,null);
                                //$this->redirect('Auth/login');
                            }
                            if ($cabinUrl){
                                $info['url'] = C('S_ZS_DOMAIN').'Auth/login?redirect_uri='.$cabinUrl;
                            }else{
                                $info['url'] = U('Auth/login');
                            }
                        }
                    }
                }
            }
            $this->ApiReturn($code,$msg,$info);
        } else {
            if($this->mid){
                $sfzh = M('Member')->where(['id'=>$this->mid])->getField('id_number');
                $this->assign('sfzh',$sfzh);
            }
            if (I('get.redirect_uri')){
                $this->assign('redirect_uri',I('get.redirect_uri'));
            }
            $this->assign('moduleName','修改手机号');
            $this->display('modifyphone');
        }
    }
//    public function modifyPhone()
//    {
//        if (IS_POST) {
//            $phone = I('post.phone');
//            $sms_code = I('post.sms_code');
//            $cabinUrl = urlencode(I('post.redirect_uri'));
//            $msg = '缺少必填参数';
//            if (!empty($phone) && !empty($sms_code)) {
//                $msg = '短信验证码错误';
//                if ($this->_varifyActivation($phone,'mobile',$sms_code)) {
//                    $save = ['phone'=>$phone];
//                    //修改成功后需要重新登录
//                    $this->memberdb->startTrans();
//                    $Yphone = $this->memberdb->where(['id'=>$this->mid])->getField('phone');
//                    if ($Yphone != $save['phone']) {
//                        if ($this->memberdb->where(['id'=>$this->mid])->setField($save)) {
//
//                            $url = 'http://localhost/cabin/cabin/Member/Register/modifyPhone';//乘务退出登录的接口地址
//                            $data = ['phone'=>$phone,'origin_phone'=>$Yphone];
//                            $re = json_decode($this->httpPsot($url,$data),true);
//                            if ($re['code'] == 1) {
//                                $this->memberdb->commit();
//                                $code = 1;
//                                $msg = '修改成功，请重新登录';
//
//
//                                $url = 'http://localhost/cabin/cabin/Member/Login/logoutApi';//乘务退出登录的接口地址
//                                $data = array('token'=> $this->token);
//
//                                $re1 = json_decode($this->httpPsot($url,$data),true);
//                                if ($re1['code'] == 1) {
//                                    session('user_name',null);
//                                    session('token',null);
//                                    S($this->token,null);
//                                    //$this->redirect('Auth/login');
//                                }
//                                if ($cabinUrl){
//                                    $info['url'] = /*U('Auth/login?redirect_uri='.$cabinUrl)*/'http://localhost/cauc_zs3/lqgl/Auth/login?redirect_uri='.$cabinUrl;
//                                }else{
//                                    $info['url'] = U('Auth/login');
//                                }
//
//                            }else{
//                                $msg = '修改失败，请重试';
//                            }
//                        }else{
//                            $this->memberdb->rollback();
//                        }
//                    }
//                }
//            }
//            $this->ApiReturn($code,$msg,$info);
//        } else {
//            /*if($_SESSION['auth']){
//                $yc_auth_key = sysmd5(C('ADMIN_ACCESS').$_SERVER['HTTP_USER_AGENT']);
//                list($user['id'],$user['mobile'],$user['name'],$user['token']) = explode("-", authcode($_SESSION['auth'], 'DECODE', $yc_auth_key));
//                $sfzh = M('Member')->where(['phone'=>$user['mobile']])->getField('id_number');
//                $this->assign('sfzh',$sfzh);
//            }*/
//            if($this->mid){
//                $sfzh = M('Member')->where(['id'=>$this->mid])->getField('id_number');
//                $this->assign('sfzh',$sfzh);
//            }
//            if (I('get.redirect_uri')){
//                $this->assign('redirect_uri',I('get.redirect_uri'));
//            }
//            $this->display('modifyphone');
//        }
//    }
    //修改密码
    public function modifyPassword()
    {
        if (IS_POST) {
            $oldPhone = I('post.oldPhone');
            $newPassword = I('post.newPassword');
            $repeatNewPassword = I('post.repeatNewPassword');
            $msg = '缺少必填参数';
            if (!empty($oldPhone) && !empty($newPassword) && !empty($repeatNewPassword)) {
                $msg = '两次输入密码不同';
                if ($newPassword == $repeatNewPassword) {
                    $save = ['password'=>md5($newPassword)];
                    $user_info = $this->memberdb->where(['id'=>$this->mid])->field('id,phone,password,user_name')->find();
                    $msg = '旧密码不正确';
                    if (md5($oldPhone) == $user_info['password']) {
                        $msg = '不可与原密码重复';
                        if ($user_info['password'] != $save['password']) {
                            //修改成功后需要重新登录
                            if ($this->memberdb->where(['id'=>$this->mid])->setField($save)) {
                                $code = 1;
                                $msg = '修改成功，已重新登录';
                                $this->get_token($user_info['phone'],$newPassword,$user_info['id']);
                                session('user_name',$user_info['user_name']);
                                $info['url'] = session('login_redirect_uri');
                            }
                        }
                    }
                }
            }
            $this->ApiReturn($code,$msg,$info);
        } else {
            $this->assign('moduleName','修改密码');
            $this->display('modifypassword');
        }
    }
    
    //报名--转专业
    public function changeSpeciality()
    {
        $info = $this->get_member_info($this->mid);//个人信息
        $thisZymc = str_replace('（','(',$info['zyname']);//专业名称
        $temp = explode('(',$thisZymc);
        $zyname = is_null($temp[0])?'':$temp[0];
        if ($info == false) {
            $this->redirect('Index/index');die;
        } else {
            $info['collegeName'] = M('College')->where(['cid'=>$info['college']])->getField('title');//学院名
            $user_bm = M('bm')->where(['mid'=>$this->mid,'type'=>1])->find();//是否已经报名
            $data = M('bm_options')->where(array('bm_type'=>1))->field('end_time')->find();//
            $data['bm_time_status'] = 1; //默认1 可报名
            if ($data['end_time'] < time()) {
                $data['bm_time_status'] = 0; //报名截止时间已过 不可报名
            }
            //未报名人员
            if ($user_bm == false) {
                //是否在导出后台名单中
                $accessList = M('Accesszzy')->where('year = '.$info['year'])->field('ksh')->select();
                if (false != $accessList){
                    $accessArr = array_column($accessList,'ksh'); //考生号数组
                    if (in_array($info['ksh'],$accessArr)){
                        //不能选自己的专业，且是所有除飞行技术、工科试验班的本科的专业
                        if(!$info['zydm']) $info['zydm'] = '';//暂时，若无数据可取时，让其不为null
                        $zy = M('zy')->Table(C('DB_PREFIX')."zy a")->Join(C('DB_PREFIX').'plan'.$info['year'].' b on b.zydm=a.zydm')->where(['a.year = '.$info['year'],'a.ccdm'=>1,'a.zydm'=>array('not in',array($info['zydm'],'081805','00600')),'b.provinceid'=>array('neq',0)])->field('a.id,a.zydm,a.zymc,a.zyfx,b.kldm')->order('a.college desc')->select();
                        //dump($info);
                        //echo M('zy')->getLastSql();die;
                        $zy_final_ws = $zy_final_lg = $zy_final_zh = $zy_forZ = [];
                        foreach ($zy as $k=>$v){ //文科类考生只能转文科，理科只能转入理工专业
                            if ($v['kldm'] == 1){
                                $zy_final_ws[$v['zydm']] = $v;
                            }
                            $zy_final_lg[$v['zydm']] = $v;
                            /*elseif($v['kldm'] == 5){
                                $zy_final_lg[$v['zydm']] = $v;
                            }*/
                            $zy_forZ[$v['zydm']] = $v;
                        }
                        if ($info['kldm'] == 1){//文史
                            $zy = $zy_final_ws;
                        }elseif($info['kldm'] == 5){ //理工
                            //$zy = M('zy')->where(['year = '.$info['year'],'ccdm'=>1])->field('id,zydm,zymc,zyfx')->order('college desc')->select();
                            $zy = $zy_final_lg;
                            if ($info['zydm'] == '00600'){ //工科实验班如果分数没超过90，只能选择志愿内的专业
                                if (($info['tdcj'] < $info['zgf'])){
                                    $map = [];
                                    $map['year'] = $info['year'];
                                    $map['provinceid'] = $info['provinceid'];
                                    $map['zydh'] = array('in',array($info['zymc_b'],$info['zymc_c'],$info['zymc_d'],$info['zymc_e'],$info['zymc_f'],$info['zymc_g']));
                                    $zyzyList = M('tJhk')->where($map)->field('zydm')->select();//志愿专业代码列表
                                    $zydmArr = array_column($zyzyList,'zydm');
                                    $zydmArr = array_merge(array_diff($zydmArr, array($info['zydm'])));//剔除志愿中已录取专业
                                    if (empty($zydmArr)){
                                        $this->assign('pc_error',1);
                                        $zy = false;
                                    }else{
                                        $zy = M('zy')->where(['year = '.$info['year'],'ccdm'=>1,'zydm'=>array('in',$zydmArr)])->field('id,zydm,zymc,zyfx')->order('college desc')->select();
                                    }
                                }
                            }
                        }elseif($info['kldm'] == 'Z'){//综合改革，从选考科目中取符合的专业
                            $myXkkm = explode('*',$info['xkkm']);
                            for ($i=0;$i<count($myXkkm);$i++){
                                $myXkkm[$i] = intval($myXkkm[$i]);
                            }

                            $subjectList = M('Subject')->where(['year'=>$info['year'],'provinceid'=>$info['provinceid'],'zydm'=>array('not in',array('081805','00600',$info['zydm']))])->field('zydm,major as zymc,zyfx,xkkm')->select();
                            $final_zy = [];
                            foreach ($subjectList as $k=>$v){
                                $v['id'] = $zy_forZ[$v['zydm']]['id'];
                                if ($v['xkkm'] == 0){ //选考科目不限，可转
                                    $final_zy[] = $v;
                                }else{
                                    $xkkmArr = explode('+',$v['xkkm']);
                                    for ($i=0;$i<count($xkkmArr);$i++){
                                        $xkkmArr[$i] = intval($xkkmArr[$i]);
                                    }
                                    $sameArr = array_intersect($myXkkm,$xkkmArr); //该考生选考科目与该科目选考科目公共的科目，即只要有一科满足即可转专业
                                    if ($sameArr){
                                        $final_zy[] = $v;
                                    }
                                }
                            }
                            $zy = $final_zy;
                        }
                    }else{
                        $this->assign('pc_error',1);
                        $zy = false;
                    }
                }else{
                    $this->assign('pc_error',1);
                    $zy = false;
                }
                $this->assign('zy',$zy);
            }
            //已经报名 
            else {
                $one = M('zy')->where(['id'=>$user_bm['zyid_one']])->field('zymc,zyfx')->find();
                $two = M('zy')->where(['id'=>$user_bm['zyid_two']])->field('zymc,zyfx')->find();
                $bm_info['zy_one_mc'] = $one['zymc'];
                $bm_info['zy_two_mc'] = $two['zymc'];
                $this->assign('bm_info',$bm_info);
                $this->assign('user_bm_status',$user_bm['status']);
            }
            $info['zyname'] = $zyname;
            $this->assign('info',$info);
            if($info['provinceid'] == 44){
                $url = substr($info['year'],2,2).'44';
                $this->assign('url',$url);
            }
            $remark = M('Remark')->where('category_id = 50')->getField('content');
            $this->assign('remark',$remark);
            $this->assign('data',$data);
            $this->display('changespeciality');
        }
       
    }
    
    //下载报名表(转专业)
    /*public function zzyDownload()
    {
        $info = $this->get_member_info($this->mid);
        $thisZymc = str_replace('（','(',$info['zyname']);
        $temp = explode('(',$thisZymc);
        $info['zyname'] = is_null($temp[0])?'':$temp[0];
        if ($info == false) {
            $this->redirect('Index/index');die;
        } else {
            if ($info['provinceid'] == 44){
                $imgUrl = 'http://www.cauc.edu.cn/lqgl/kszp/'.$info['year'].'/44/'.substr($info['year'],2,2).'44'.$info['ksh'].'.jpg';
            }else{
                $imgUrl = 'http://www.cauc.edu.cn/lqgl/kszp/'.$info['year'].'/'.$info['provinceid'].'/'.$info['ksh'].'.jpg';
            }
            $xhInfo = M('Info'.$info['year'])->where(['sfzh'=>$info['sfzh']])->find();
            $collegeName = M('College')->where(['cid'=>$info['college']])->getField('name');
            $user_bm = M('bm')->where('mid = '.$this->mid.' and type = 1')->find();
            if ($user_bm != false) {
                $one = M('zy')->where(['id'=>$user_bm['zyid_one']])->field('zymc,zyfx')->find();
                $two = M('zy')->where(['id'=>$user_bm['zyid_two']])->field('zymc,zyfx')->find();
//                $zy_one_mc = $one['zyfx'] == '' ? $one['zymc'] : $one['zymc'].'('.$one['zyfx'].')';
//                $zy_two_mc = $two['zyfx'] == '' ? $two['zymc'] : $two['zymc'].'('.$two['zyfx'].')';
                $zy_one_mc = $one['zymc'];
                $zy_two_mc = $two['zymc'];
                $html= '
                <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
                <head>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
                <xml><w:WordDocument><w:View>Print</w:View></xml>
                </head>
                <body>
                <h3 style="text-align: center">本科新生转专业申请表</h3>
                <table border="1" cellspacing="0" cellpadding="3" width="600" style="height: 40px">
                <tr >
                <td width="300" style="text-align: center" colspan="5" >学生基本信息</td>
                </tr>
                <tr >
                <td width="120" height="160" style="text-align: center" colspan="1" rowspan="3"><img src="'.$imgUrl.'" width="120" height="160"/></td>
                <td width="140" style="text-align: center" colspan="1" >姓名</td>
                <td width="140" style="text-align: center" colspan="1" >'.$info['xm'].'</td>
                <td width="160" style="text-align: center" colspan="1" >生源地</td>
                <td width="160" style="text-align: center" colspan="1" >'.$info['name'].'</td>
                </tr>
                <tr >
                <td width="140" style="text-align: center" colspan="1" >性别</td>
                <td width="140" style="text-align: center" colspan="1" >'.$info['xbmc'].'</td>
                <td width="160" style="text-align: center" colspan="1" >学院</td>
                <td width="160" style="text-align: center" colspan="1" >'.$collegeName.'</td>
                </tr>
                 <tr >
                <td width="140" style="text-align: center" colspan="1" >班级</td>
                <td width="140" style="text-align: center" colspan="1" >'.$xhInfo['bj'].'</td>
                <td width="160" style="text-align: center" colspan="1" >学号</td>
                <td width="160" style="text-align: center" colspan="1" >'.$xhInfo['xh'].'</td>
                </tr>
                 <tr >
                <td width="140" style="text-align: center" colspan="1" >身份证号</td>
                <td width="160" style="text-align: center" colspan="2" >'.$info['sfzh'].'</td>
                <td width="140" style="text-align: center" colspan="1" >考生号</td>
                <td width="160" style="text-align: center" colspan="1" >'.$info['ksh'].'</td>
                </tr>
                 <tr >
                <td width="140" style="text-align: center" colspan="1" >投档成绩</td>
                <td width="160" style="text-align: center" colspan="2" >'.$info['tdcj'].'</td>
                <td width="140" style="text-align: center" colspan="1" >科类</td>
                <td width="160" style="text-align: center" colspan="1" >'.$info['kl'].'</td>
                </tr>
                 <tr >
                <td width="140" style="text-align: center" colspan="1" >原专业</td>
                <td width="160" style="text-align: center" colspan="2" >'.$info['zyname'].'</td>
                <td width="140" style="text-align: center" colspan="1" >手机号</td>
                <td width="160" style="text-align: center" colspan="1" >'.$info['phone'].'</td>
                </tr>
                 <tr >
                <td width="140" style="text-align: center" colspan="1" >拟转专业1</td>
                <td width="160" style="text-align: center" colspan="2" >'.$zy_one_mc.'</td>
                <td width="140" style="text-align: center" colspan="1" >拟转专业2</td>
                <td width="160" style="text-align: center" colspan="1" >'.$zy_two_mc.'</td>
                </tr>
                 <tr>
                <td width="170" colspan="3" ><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;以上信息核对无误
                <br><br><br><br>本人签字：</td>
                <td width="170" colspan="2" ><br><br>&nbsp;&nbsp;&nbsp;&nbsp;有效证件核验无误
                <br><br><br><br>年级主任签字：</td>
                </tr>
                <tr>
                 <td width="170" colspan="3">转出学院意见：
                 <br><br><br><br><br><br>&nbsp;&nbsp;盖章：<br>
                </td>
                 <td width="170" colspan="2">教务处意见：
                 <br><br><br><br><br><br>&nbsp;&nbsp;盖章：<br>
                </td>
                </tr>  
                <tr>
                 <td width="140" style="text-align: center" colspan="1" >转入专业</td>
                <td width="160" style="text-align: center" colspan="2" ></td>
                <td width="140" style="text-align: center" colspan="1" >转入班级</td>
                <td width="160" style="text-align: center" colspan="2" ></td>
                </tr>
                </table>
                <p style="font-size: 15px;">&nbsp;&nbsp;注：1.若申请转入专业志愿1不符合专业要求，学校将按申请转入专业志愿2进行专业调整，若还不符合，则仍在原专业就读。<br>
                &nbsp;&nbsp;&nbsp;&nbsp;2.申请者须仔细阅读相关专业转入要求，本表学生基本信息均为系统生成，手写无效。<br>
                &nbsp;&nbsp;&nbsp;&nbsp;3.参加中欧选拔，且已确认转入中欧学院者，此表失效。<br>
                </p>
                </body></html>';
//                ob_start(); //打开缓冲区
//                header("Cache-Control:no-store");
//                header("Content-type: application/octet-stream");
//                header("Accept-Ranges: bytes");
//                if (strpos($_SERVER["HTTP_USER_AGENT"],'MSIE')) {
//                    header('Content-Disposition: attachment; filename=本科新生转专业申请表.docx');
//                }else if (strpos($_SERVER["HTTP_USER_AGENT"],'Firefox')) {
//                    header('Content-Disposition: attachment; filename=本科新生转专业申请表.docx');
//                } else {
//                    header('Content-Disposition: attachment; filename=本科新生转专业申请表.docx');
//                }
//                header("Pragma:no-cache");
//                header("Expires:0");
//                ob_end_flush();//输出全部内容到浏览器

                $content = htmlspecialchars_decode($html); //想要保存的html （从数据库取的值，可能需要反编译一下，自行判断）
                $word = $this->getWordDocument($content,'http://www.cauc.edu.cn/lqgl/');

                //$fileName = str_replace(' ','',$title ); //（我的保存时，不能出现空格，有的话会没有后缀，自行判断）
                if($word){
                    ob_start(); //开始输出缓冲
                    header("Cache-Control: no-cache, must-revalidate");
                    header("Pragma: no-cache");
                    header("Content-Type: application/doc");
                    header("Content-Disposition: attachment; filename=" . '本科新生转专业申请表' . ".doc");
                    ob_end_clean();//结束输出缓冲，清洁（擦除）输出缓冲区并关闭输出缓冲
                    echo $word;
                    exit;
                }


//                header("Content-type: application/octet-stream");
//                header("Accept-Ranges: bytes");
//                header("Accept-Length: ".strlen($html));
//                header('Content-Disposition: attachment; filename=本科新生转专业申请表.doc');
//                header("Pragma:no-cache");
//                header("Expires:0");
//                echo $html;

            }
        }
    }*/
    
    //中欧选拔
    public function collegeSelection()
    {
        $info = $this->get_member_info($this->mid);
        if ($info == false) {
            $this->redirect('Index/index');die;
        } else {
            $bm = M('bm')->where(['mid' => $this->mid, 'type' => 2])->find();
            $data = M('bm_options')->where(array('bm_type' => 2))->field('end_time')->find();
            $data['bm_time_status'] = 1; //默认1 可报名
            if ($data['end_time'] < time()) {
                $data['bm_time_status'] = 0; //报名截止时间已过 不可报名
            }
            $this->assign('info', $info);
            if($info['provinceid'] == 44){
                $url = substr($info['year'],2,2).'44';
                $this->assign('url',$url);
            }
            $this->assign('bm', $bm);
            $this->assign('data', $data);
            $this->display('collegeselection');
        }
    }
    
    //报名
    public function SubSignUp()
    {
        $type = I('post.type');
        if (in_array($type,[1,2])) {
            $code = -1;
            $data = M('bm_options')->where(array('bm_type'=>$type))->field('end_time')->find();
            if ($data['end_time'] < time()) {
                $msg = '报名已经结束';
                $this->ApiReturn($code,$msg);
            }
            $add = [
                'mid'=>$this->mid,
                'type'=>$type,
                'create_time'=>time(),
            ];
            if ($type == 1) {
                $info = $this->get_member_info($this->mid);
                //是否在导出后台名单中
                $accessList = M('Accesszzy')->where('year = '.$info['year'])->field('ksh')->select();
                if (false != $accessList){
                    $accessArr = array_column($accessList,'ksh'); //考生号数组
                    if (in_array($info['ksh'],$accessArr)){
                        $msg = true;
                    }else{
                        $msg = '您不符合转专业报名条件，提交失败';
                    }
                }else{
                    $msg = '转专业工作暂未开始，提交失败';
                }
                if ($msg != true){
                    $this->ApiReturn($code,$msg);
                }

                $zyid_one = I('post.zyid_one');
                $zyid_two = I('post.zyid_two');
                $msg = '请选择则志愿';
                if (empty($zyid_one) || empty($zyid_two)) $this->ApiReturn($code,$msg);
                $add['zyid_one'] = $zyid_one;
                $add['zyid_two'] = $zyid_two;
            }else if ($type == 2) {
                $qq = I('post.qq');
                $msg = '请填写qq号';
                if (empty($qq)) $this->ApiReturn($code,$msg);
                $add['qq'] = $qq;
            }
            try {
                if (M('bm')->add($add)) {
                    $code = 1;
                    $msg = '提交成功';
                }
            } catch (\Exception $e) {
                $msg = '系统错误';
            }
            $this->ApiReturn($code,$msg);
        }
        die;
    }
    
    //空乘/空保
    public function AeronauticalAttendants()
    {
        $token = $this->token;
        //redirect('http://localhost/cabin/cabin/Member/Register/login?token='.$token);
        redirect(C('S_DOMAIN').'Member/Register/protocal?token='.$token);
    }
    
    //获取学生信息
    public function get_member_info($mid)
    {
        $memberInfo = $this->memberdb->where(['id'=>$mid])->field('id_number,create_time,phone')->find();
        $year = date("Y");
        $Model = 't_tdd_final'.$year; //注册时减去一年
        $tdd = D($Model);
        $Model1 = 'cj'.$year; //注册时减去一年
        $tddCj = D($Model1);
        $info = $tdd
            ->join([
                'LEFT JOIN ycity_xbdm ON ycity_'.$Model.'.xbdm = ycity_xbdm.xbdm',
                'LEFT JOIN ycity_province ON ycity_'.$Model.'.provinceid = ycity_province.id',
                'LEFT JOIN ycity_t_jhk ON ycity_'.$Model.'.lqzy = ycity_t_jhk.zydh',
                'LEFT JOIN ycity_zy ON ycity_t_jhk.zydm = ycity_zy.zydm'
            ])
            ->where(['sfzh'=>$memberInfo['id_number']])
            ->field('ycity_'.$Model.'.xm,ycity_'.$Model.'.pc,ycity_'.$Model.'.lqzy,ycity_'.$Model.'.kldm,ycity_'.$Model.'.xkkm,ycity_'.$Model.'.tdcj,ycity_'.$Model.'.ksh,ycity_'.$Model.'.year,ycity_xbdm.xbmc,ycity_xbdm.xbdm,ycity_'.$Model.'.sfzh,ycity_'.$Model.'.ksh,ycity_'.$Model.'.cj,ycity_'.$Model.'.provinceid,ycity_province.province,ycity_'.$Model.'.lxsj,ycity_'.$Model.'.lxdh,ycity_'.$Model.'.tddw,ycity_'.$Model.'.zymc_b,ycity_'.$Model.'.zymc_c,ycity_'.$Model.'.zymc_d,ycity_'.$Model.'.zymc_e,ycity_'.$Model.'.zymc_f,ycity_'.$Model.'.zymc_g,ycity_zy.zymc,ycity_zy.zyfx,ycity_zy.college')
            ->order('ycity_'.$Model.'.id desc')
            ->find();
        if ($info == false) return false;

        $major = $info['lqzy'];
        $zy = M('tJhk')->where('year='.$info['year'].' AND provinceid='.$info['provinceid']." AND zydh='$major'")->field('zydm,zymc,jhxz,year,provinceid')->find();
        $info['zyname'] = correctZyname($zy);
        $info['zydm'] = $zy['zydm'];
        $info['ccdm'] = M('Zy')->where(['year'=>$year,'zydm'=>$zy['zydm']])->getField('ccdm');//本专科
        if (($zy['provinceid'] == 15 and $zy['jhxz'] == 1) OR (strstr($zy['zymc'],'定向'))){
            //sfdx是否定向
            $info['sfdx'] = 1;//定向
        }else{
            $info['sfdx'] = 2;//非定向
        }
//        print_r($tdd->getLastSql());die;
        if (in_array($info['provinceid'],[31,33])) {
            $xkkm = explode('*',$info['xkkm']);
            //$kl = M('td_cjxdm')->where(['year'=>$info['year'],'provinceid'=>$info['provinceid'],'cjxdm'=>['in',$xkkm]])->getField('cjxmc',true);
            //$info['kl'] = implode(',',$kl);
            $info['cjx_cj'] = $tddCj->where(['ksh'=>$info['ksh'],'cjxdm'=>['in',$xkkm]])->getField('cj',true);//分类成绩
        } else {
            //$info['kl'] = M('td_kldm')->where('kldm = '."'".$info['kldm']."'".' and year = '.$info['year'].' and provinceid ='.$info['provinceid'])->getField('klmc');
        }
        $info['kldm_origin'] = $info['kldm'];

        //纠正科类代码
        if ($info['provinceid'] == 32){
            if ($info['kldm'] == 2){
                $info['kldm'] = 5;
            }
        }else{
            $tddwkldm = M('CorrectTddw')->where(['year'=>$year,'provinceid'=>$info['provinceid'],'tddw'=>$info['tddw']])->getField('kldm');
            $info['kldm'] = $tddwkldm?$tddwkldm:$info['kldm'];//纠正个别省份科类文理综合分文理
            $xnkldm = M('CorrectKldm')->where(['year'=>$year,'provinceid'=>$info['provinceid'],'kldm_origin'=>$info['kldm']])->getField('kldm');
            $info['kldm'] = ($xnkldm!='')?$xnkldm:$info['kldm']; //纠正个别省份科类代码
        }//Select kldm from ycity_correct_kldm where year=2017 and provinceid=45 and kldm_origin = $info['kldm'];
        switch ($info['kldm']){
            case 5 : $info['kl'] = '理工';break;
            case 1 : $info['kl'] = '文史';break;
            case 'Z' : $info['kl'] = '综合改革';break;
            case 0 : $info['kl'] = '文理综合';break;
        }
        //SELECT * FROM ycity_zzy WHERE year = 2018 and provinceid = 43 and kldm = 5
        $zgf = M('Zzy')->where(['year'=>$year,'provinceid'=>$info['provinceid'],'kldm'=>$info['kldm']])->getField('fraction');//转专业资格分
        if ($zgf && $zgf != 0){ //省控线
            $info['zgf'] = $zgf;
        }
        /*$skx = M('Skx')->where(['year'=>$year,'province'=>$info['provinceid'],'kldm'=>$info['kldm']])->getField('skx');//保证有省控线
        if ($skx && $skx != 0){ //省控线
            $info['skx'] = $skx;

            $standard_score = M('Standardscore')->where('year = '.$year.' and province = '.$info['provinceid'])->getField('score'); //该省高考总分
            $info['zhcj'] = round(750 * $info['tdcj'] / $standard_score,2); //折后成绩

            $info['zhskx'] = round(750 * $skx / $standard_score,2); //折算成750总分的省控线
            $info['zhfc'] = $info['zhcj'] - $info['zhskx']; //折后分数 - 折后省控线
        }*/
        $xhInfo = M('Info'.$info['year'])->where(['sfzh'=>$info['sfzh']])->find();
        $info['xh'] = $xhInfo['xh'];//学号
        $info['bj'] = $xhInfo['bj'];//班级
        $info['tdcj'] = floor($info['tdcj']);//投档成绩
        $info['phone'] = $memberInfo['phone'];//手机号
        return $info;
    }
    
    //高水平运动员报名页
    public function highLevelAthletes()
    {
        $where = ['mid'=>$this->mid];
        $bmxx = M('Gspydybm')->where($where)->find();
        $where['status'] = 1;
        $bkxm = M('gspydybkxm')->where($where)->field('status',true)->select();
        $view_file_name = 'highlevelathletes';
        if ($bmxx != false) {
            $bmxx['shgx'] = json_decode($bmxx['shgx'],true);
            $bmxx['grjl'] = json_decode($bmxx['grjl'],true);
            $bmxx['ydcj'] = json_decode($bmxx['ydcj'],true);
            
            if ($bmxx['gkbmcl'] == ''){
                $this->assign('noImport',1);
            }
            $this->assign('bmxx',$bmxx);
            $ispublish = M('BmOptions')->where('bm_type = 4')->getField('registration_switch');
            $this->assign('ispublish',$ispublish);
            $view_file_name = 'highlevelathletesinfo';
        }else{
            $open = M('BmOptions')->where('bm_type = 5')->getField('registration_switch');
            if ($open != 1){
                $this->redirect('Index/index');
            }
        }
        $this->assign('bkxm',$bkxm);
        $provinceList = M('Province')->where('id != 0')->field('id,name')->select();
        $this->assign('provinceList',$provinceList);
        $this->display($view_file_name);
    }
    //高水平运动员报名--返回修改
    public function returnModification()
    {
        $where = ['mid'=>$this->mid];
        $bmxx = M('Gspydybm')->where($where)->find();
        $bkxm = M('gspydybkxm')->where($where)->field('status',true)->select();

        if ($bmxx != false) {
            $bmxx['shgx'] = json_decode($bmxx['shgx'],true);
            $bmxx['grjl'] = json_decode($bmxx['grjl'],true);
            $bmxx['ydcj'] = json_decode($bmxx['ydcj'],true);
            if ($bmxx['bm_status'] == 2) {
                $view_file_name = 'returnmodification';
                $this->assign('bkxm',$bkxm);
            } else {
                $view_file_name = 'highlevelathletesinfo';
            }
        } else {
            $view_file_name = 'highlevelathletes';
        }
        $this->assign('hjszd',$bmxx['hjszd']);
        $this->assign('bmxx',$bmxx);
        if ($bmxx['gkbmcl'] == ''){
            $this->assign('noImport',1);
        }
        $provinceList = M('Province')->where('id != 0')->field('id,name')->select();
        $this->assign('provinceList',$provinceList);
        $this->display($view_file_name);
    }
    //高水平运动员报名--提交
    public function SubSignUpAthletes()
    {
        C('TOKEN_ON',false);
        $post = I('post.');
        if (!empty($post)) {
            $post['mid'] = $this->mid;
            $post['shgx'] = json_encode(['shgx_fq_mz'=>$post['shgx_fq_mz'],'shgx_fq_dh'=>$post['shgx_fq_dh'],'shgx_fq_gzdw'=>$post['shgx_fq_gzdw'],
                'shgx_mq_mz'=>$post['shgx_mq_mz'],'shgx_mq_dh'=>$post['shgx_mq_dh'],'shgx_mq_gzdw'=>$post['shgx_mq_gzdw']]);
            $post['grjl'] = json_encode($post['grjl']);
            $post['ydcj'] = json_encode($post['ydcj']);
            $gspydybm = D('Gspydybm');
            //判断是否报名过
            $bmxx = M('Gspydybm')->where(['mid'=>$this->mid])->find();
            if ($bmxx != false) {
                //判断是否是返回修改状态
                if ($bmxx['bm_status'] == 2) {
                    $post['id'] = $bmxx['id'];
                    $post['update_time'] = time();
                    $post['bm_status'] = 1;
                    if ($gspydybm->save($post)) {
                        $info['url'] = U('Index/highLevelAthletes');
                        $this->ApiReturn(1,'修改提交成功',$info);
                    } else {
                        $this->ApiReturn(-1,'没有修改');
                    }
                } else {
                    $this->ApiReturn(-1,'不可修改提交');
                }
            } else {
                $post['bm_status'] = 1;
                $post['bm_time'] = time();
                $data = $gspydybm->create($post);
                if ($data != false) {
                    if ($gspydybm->add($data)) {
                        $content = M('Message')->where('id = 9')->getField('content');
                        if ($content == ''){
                            $content = '您好，'.$bmxx['xm'].'同学已完成报名，请等待审核！';
                        }
                        $phone = M('Member')->where(['id'=>$this->mid])->getField('phone');
                        $res = $this->_sendSMS($phone,$content);
                        if (false != $res){
                            $this->ApiReturn(1,'报名成功');
                        }else{
                            $this->ApiReturn(-1,'短信发送失败');
                        }
                    } else {
                        $this->ApiReturn(-1,'报名失败');
                    }
                } else {
                    $this->ApiReturn(-1,$gspydybm->getError());
                }
            }
            
        } else {
            $this->ApiReturn(-1,'请填写报名信息');
        }
    }

    protected function _sendSMS($mobile,$content){
        $data['mobile'] = $mobile;
        $data['time'] = time();
        $data['status'] = 2; //发送通知
        $daoAdd = M('Activation')->add($data);
        if (false !== $daoAdd) {
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, "http://sms-api.luosimao.com/v1/send.json");

            curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 30);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
            curl_setopt($ch, CURLOPT_HEADER, FALSE);

            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, TRUE);
            curl_setopt($ch, CURLOPT_SSLVERSION, 3);

            curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
            curl_setopt($ch, CURLOPT_USERPWD, 'api:key-03254a3e83e9d7bb06d51046bb4559fa');


            curl_setopt($ch, CURLOPT_POST, TRUE);
            curl_setopt($ch, CURLOPT_POSTFIELDS, array('mobile' => $data['mobile'],'message' => $content.'【中国民航大学】'));

            $res = curl_exec($ch);
            curl_close($ch);

            $res_decode = json_decode($res,true);

            switch ($res_decode->error) {
                case 0:
                    Log::write('[' . date('Y-m-d h:i:s') . '][' . $mobile . ']短信接口状态码：0，信息发送成功。', Log::INFO);
                    break;
                case -10:
                    Log::write('[' . date('Y-m-d h:i:s') . '][' . $mobile . ']短信接口状态码：-10，验证信息失败，检查api key是否和各种中心内的一致，调用传入是否正确。', Log::INFO);
                    break;
                case -20:
                    Log::write('[' . date('Y-m-d h:i:s') . '][' . $mobile . ']短信接口状态码：-20，短信余额不足，进入个人中心购买充值。', Log::INFO);
                    break;
                case -30:
                    Log::write('[' . date('Y-m-d h:i:s') . '][' . $mobile . ']短信接口状态码：-30，短信内容为空，检查调用传入参数：message。', Log::INFO);
                    break;
                case -31:
                    Log::write('[' . date('Y-m-d h:i:s') . '][' . $mobile . ']短信接口状态码：-31，短信内容存在敏感词，修改短信内容，更换词语。', Log::INFO);
                    break;
                case -32:
                    Log::write('[' . date('Y-m-d h:i:s') . '][' . $mobile . ']短信接口状态码：-32，短信内容缺少签名信息，短信内容末尾增加签名信息eg.【公司名称】。', Log::INFO);
                    break;
                case -40:
                    Log::write('[' . date('Y-m-d h:i:s') . '][' . $mobile . ']短信接口状态码：-40，错误的手机号，检查手机号是否正确。', Log::INFO);
                    break;
                case -50:
                    Log::write('[' . date('Y-m-d h:i:s') . '][' . $mobile . ']短信接口状态码：-50，请求发送IP不在白名单内，查看触发短信IP白名单的设置。', Log::INFO);
                    break;
                default:
                    Log::write('[' . date('Y-m-d h:i:s') . '][' . $mobile . ']短信接口状态码：无', Log::INFO);
            }
            return $res_decode;
        } else{
            return false;
        }
    }

    //高水平运动员报名--上传证明文件
    public function uploads()
    {
        $upload = new \Think\Upload();// 实例化上传类
        $upload->maxSize   =     3145728 ;// 设置附件上传大小
        $upload->exts      =     array('jpg', 'gif', 'png', 'jpeg');// 设置附件上传类型
//        $upload->exts      =     array('jpg');// 设置附件上传类型
        $upload->rootPath  =     UPLOAD_PATH; // 设置附件上传根目录
        $upload->savePath  =     '/SeniorAthlete/'; // 设置附件上传（子）目录
        // 上传文件
        $info   =   $upload->upload();
        if(!$info) {// 上传错误提示错误信息
            $this->ajaxReturn(['code'=>-1,'msg'=>$upload->getError()]);
        }else{// 上传成功
//            $this->ajaxReturn(['code'=>1,'msg'=>'上传成功','data'=>['url'=>$info['file']['savepath'].$info['file']['savename'],'imgUrl'=>'http://'.$_SERVER['SERVER_NAME'].UPLOAD_PATH.$info['file']['savepath'].$info['file']['savename']]]);
            $this->ajaxReturn(['code'=>1,'msg'=>'上传成功','data'=>['url'=>$info['file']['savepath'].$info['file']['savename'],'imgUrl'=>'.'.UPLOAD_PATH.$info['file']['savepath'].$info['file']['savename']]]);
        }
    }
    //高水平运动员报名--打印报名表
    public function pdf() {
        $id = intval(I('get.id'));
        $data = M('Gspydybm')
            ->join('LEFT JOIN ycity_gspydybkxm ON ycity_gspydybm.bkxm_id = ycity_gspydybkxm.id')
            ->field('ycity_gspydybm.*,ycity_gspydybkxm.xmmc')
            ->where(['ycity_gspydybm.id'=>$id])
            ->find();
        if ($data != false) {
            $data['shgx'] = json_decode($data['shgx'],true);
            $data['grjl'] = json_decode($data['grjl'],true);
            $data['ydcj'] = json_decode($data['ydcj'],true);
            $phone = M('Member')->where(['id'=>$data['mid']])->getField('phone');
        }
        //引入类库
        Vendor('mpdf.mpdf');
        //设置中文编码
        $mpdf = new \mPDF('zh-cn','A4', 0, '微软雅黑', 0, 0);
        //html内容
        $html = '<table border="1" cellspacing="0" cellpadding="3" width="" align="center">
        <tr >
            <td align="center" style="font-size: 25px;" colspan="7" ><b>中国民航大学高水平运动员报名表</b></td>
        </tr>
        <tr >
            <td width="200" style="font-size: 16px;" colspan="4" >年度：'.date('Y').'</td>
            <td width="200" style="font-size: 16px;" colspan="3" >编号：'.$id.'</td>
        </tr>
        <tr >
            <td align="center" style="font-size: 16px;" colspan="7" >基本情况</td>
        </tr>
        <tr >
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >姓名</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["xm"].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">性别</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["xb"].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">出生日期</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["csny"].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" rowspan="5" colspan="1" ><img width="130" src="./Public/Uploads'.$data["zp"].'"/></td>
        </tr>
        <tr >
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >年龄</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["age"].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">民族</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["mz"].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">身份证号码</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["sfzh"].'</td>
        </tr>
         <tr >
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >政治面貌</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["zzmm"].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">高考所在地</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["hjszd"].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">联系电话</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$phone.'</td>
        </tr>
         <tr >
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >报考项目</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="2" >'.$data["xmmc"].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">位置（级别）</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="2" >'.$data["wz"].'</td>
        </tr>
        <tr >
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >运动等级</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["yddj"].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">证书编号</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="3" >'.$data["zsbh"].'</td>
        </tr>
         <tr >
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >身高</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["sg"].'cm</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">体重</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data["tz"].'kg</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="2">副项</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" ></td>
        </tr>
        <tr >
            <td align="center" style="font-size: 16px;" colspan="7" >社会关系</td>
        </tr>
        <tr >
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >父/母姓名</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data['shgx']['shgx_fq_mz'].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="2">工作单位</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data['shgx']['shgx_fq_gzdw'].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">联系电话</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data['shgx']['shgx_fq_dh'].'</td>
        </tr>
        <tr >
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >父/母姓名</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data['shgx']['shgx_mq_mz'].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="2">工作单位</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data['shgx']['shgx_mq_gzdw'].'</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1">联系电话</td>
            <td width="100" style="text-align: center;font-size: 16px;" colspan="1" >'.$data['shgx']['shgx_mq_dh'].'</td>
        </tr>
        <tr >
            <td align="center" style="font-size: 16px;" colspan="7" >个人简历<p style="font-size: 10px;">填报顺序：高中、初中、小学</p></td>
        </tr>
        <tr >
            <td align="center" style="font-size: 16px;" colspan="1" >开始时间</td>
            <td align="center" style="font-size: 16px;" colspan="1" >结束时间<br/></td>
            <td align="center" style="font-size: 16px;" colspan="4" >学校</td>
            <td align="center" style="font-size: 16px;" colspan="1" >证明人</td>
        </tr>';
        foreach ( $data['grjl'] as $grjl) {
            $html.= ' <tr><td align="center" style="font-size: 16px;" colspan="1">'.$grjl['qzsj'].'</td>
             <td align="center" style="font-size: 16px;" colspan="1" >'.$grjl['jssj'].'</td>
                <td align="center" style="font-size: 16px;" colspan="4" >'.$grjl['zmr'].'</td>
                <td  align="center" style="font-size: 16px;" colspan="1">'.$grjl['xxmc'].'</td></tr>';
        }
        $html .= '
        <tr >
            <td align="center" style="font-size: 16px;" colspan="7" >运动成绩（近三年最佳成绩）</td>
        </tr>
        <tr >
            <td align="center" style="font-size: 16px;" colspan="2" >比赛时间</td>
            <td align="center" style="font-size: 16px;" colspan="1" >比赛地点</td>
            <td align="center" style="font-size: 16px;" colspan="2" >比赛名称</td>
            <td align="center" style="font-size: 16px;" colspan="1" >比赛级别</td>
            <td align="center" style="font-size: 16px;" colspan="1" >最佳运动成绩</td>
        </tr>';
        foreach ( $data['ydcj'] as $ydcj) {
            $html.= ' <tr><td align="center" style="font-size: 16px;" colspan="2">'.$ydcj['bssj'].'</td>
                <td align="center" style="font-size: 16px;" colspan="1" >'.$ydcj['bsdd'].'</td>
                <td align="center" style="font-size: 16px;" colspan="2" >'.$ydcj['bsmc'].'</td>
                <td align="center" style="font-size: 16px;" colspan="1" >'.$ydcj['bsjb'].'</td>
                <td  align="center" style="font-size: 16px;" colspan="1">'.$ydcj['zjydcj'].'</td></tr>';
        }
        $html .= '
        <tr>
        
            <td align="center" style="font-size: 16px;" colspan="1" ><br><br><br>毕业学校<br/>推荐意见<br><br></td>
            <br><br><br><br>
            <td align="center" style="font-size: 16px;" colspan="6">&nbsp;&nbsp;'.$data['byxxtcyj'].'<p><br><br>（盖章）</p></td>
        </tr>
         <tr>
        
            <td align="center" style="font-size: 16px;" colspan="1" >考生签字<br>确认</td>
            <td align="center" style="font-size: 16px;" colspan="6"></td>
        </tr></table>';
        $mpdf->WriteHTML($html);
        $mpdf->Output();
        exit;
    }

    /**
     * 生成转专业pdf
     *
     */
    public function zzyDownload(){
        set_time_limit(60);
        ini_set("memory_limit","256M");
        $info = $this->get_member_info($this->mid);
        $thisZymc = str_replace('（','(',$info['zyname']);
        $temp = explode('(',$thisZymc);
        $info['zyname'] = is_null($temp[0])?'':$temp[0];
        if ($info == false) {
            $this->redirect('Index/index');die;
        } else {
            if ($info['provinceid'] == 44) {
                $imgUrl = '/job/cauc_zsb2/zsb/kszp/' . $info['year'] . '/44/' . substr($info['year'], 2, 2) . '44' . $info['ksh'] . '.jpg';
            } else {
                $imgUrl = '/job/cauc_zsb2/zsb/kszp/' . $info['year'] . '/' . $info['provinceid'] . '/' . $info['ksh'] . '.jpg';
            }
            $xhInfo = M('Info' . $info['year'])->where(['sfzh' => $info['sfzh']])->find();
            $collegeName = M('College')->where(['cid' => $info['college']])->getField('title');
            $user_bm = M('bm')->where('mid = ' . $this->mid . ' and type = 1')->find();
            if ($user_bm != false) {
                $one = M('zy')->where(['id' => $user_bm['zyid_one']])->field('zymc,zyfx')->find();
                $two = M('zy')->where(['id' => $user_bm['zyid_two']])->field('zymc,zyfx')->find();
//                $zy_one_mc = $one['zyfx'] == '' ? $one['zymc'] : $one['zymc'].'('.$one['zyfx'].')';
//                $zy_two_mc = $two['zyfx'] == '' ? $two['zymc'] : $two['zymc'].'('.$two['zyfx'].')';
                $zy_one_mc = $one['zymc'];
                $zy_two_mc = $two['zymc'];
            }
        }

        $xm = $info['xm'];
        $pname = $info['name'];
        $xbmc = $info['xbmc'];
        $bj = $xhInfo['bj'];
        $xh = $xhInfo['xh'];
        $sfzh = $info['sfzh'];
        $ksh = $info['ksh'];
        $tdcj = $info['tdcj'];
        $kl = $info['kl'];
        $zyname = $info['zyname'];
        $phone = $info['phone'];

        //return false;
        Vendor('tcpdf.config.lang.chi');
        Vendor('tcpdf.tcpdf');
        $pdf = new \TCPDF("P", PDF_UNIT, 'A4', true, 'UTF-8', false);
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Nicola Asuni');
        $pdf->SetTitle('本科新生转专业申请表');
        //$pdf->SetSubject('TCPDF Tutorial');
        //$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
        $pdf->SetMargins(10, 15, 10, 0);
        $pdf->SetAutoPageBreak(true, 0);
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
        $pdf->setLanguageArray($l);
        $pdf->setFontSubsetting(true);
        $pdf->SetFont('stsongstdlight', '', 12);
        //$pdf->SetFont('droidsansfallback', '', 12);
        $pdf->AddPage();

        $html_header = <<<EOF
		<table width="100%" cellspacing="0" cellpadding="0" border="0" style="text-align:center;margin:0 auto;">
			<tbody>
			<tr>					
				<td width="100%" style="font-size:50px;font-weight:bold;">本科新生转专业申请表</td>			
			</tr>	
			<tr >
                <td width="100%" height="10px" style="line-height:10px;text-align: center" colspan="5" ></td>
                </tr>
EOF;
        $html_str = <<<EOF
                    <tr>
						<td colspan="5" height="100%">
			<table cellspacing="0" cellpadding="3" border="1" class="content" style="text-align:center;margin:0 auto;">
				<tr >
                <td width="100%" height="10px" style="line-height:10px;text-align: center" colspan="5" >学生基本信息</td>
                </tr>
                <tr >
                <td width="16%" height="130" style="text-align: center" colspan="1" rowspan="3"><img src="$imgUrl" height="130" /></td>
                <td width="17%" height="45" style="line-height:10px;text-align: center" colspan="1">姓名</td>
                <td width="17%" height="45" style="line-height:10px;text-align: center" colspan="1" >$xm</td>
                <td width="25%" height="45" style="line-height:10px;text-align: center" colspan="1" >生源地</td>
                <td width="25%" height="45" style="line-height:10px;text-align: center" colspan="1" >$pname</td>
                </tr>
                <tr >
                <td width="17%" height="44" style="line-height:10px;text-align: center" colspan="1" >性别</td>
                <td width="17%" height="44" style="line-height:10px;text-align: center" colspan="1" >$xbmc</td>
                <td width="25%" height="44" style="line-height:10px;text-align: center" colspan="1" >学院</td>
                <td width="25%" height="44" style="line-height:10px;text-align: center" colspan="1" >$collegeName</td>
                </tr>
                 <tr >
                <td width="17%" height="43" style="line-height:10px;text-align: center" colspan="1" >班级</td>
                <td width="17%" height="43" style="line-height:10px;text-align: center" colspan="1" >$bj</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >学号</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >$xh</td>
                </tr>
                 <tr >
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >身份证号</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="2" >$sfzh</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >考生号</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >$ksh</td>
                </tr>
                 <tr >
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >投档成绩</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="2" >$tdcj</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >科类</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >$kl</td>
                </tr>
                 <tr >
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >原专业</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="2" >$zyname</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >手机号</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >$phone</td>
                </tr>
                 <tr >
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >拟转专业1</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="2" >$zy_one_mc</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >拟转专业2</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >$zy_two_mc</td>
                </tr>
                 <tr>
                <td width="50%" colspan="3"><br><br>以上信息核对无误
                <br><br><br><br><br><br><br><span style="text-align:left">&nbsp;&nbsp;本人签字：</span></td>
                <td width="50%" colspan="2"><br><br>有效证件核验无误
                <br><br><br><br><br><br><br><span style="text-align:left">&nbsp;&nbsp;年级主任签字：</span></td>
                </tr>
                <tr>
                 <td width="50%" colspan="3" style="text-align:left;">转出学院意见：
                 <br><br><br><br><br><br><br>&nbsp;&nbsp;盖章：<br>
                </td>
                 <td width="50%" colspan="2" style="text-align:left;">教务处意见：
                 <br><br><br><br><br><br><br>&nbsp;&nbsp;盖章：<br>
                </td>
                </tr>
                <tr>
                 <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >转入专业</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="2" ></td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="1" >转入班级</td>
                <td width="25%" height="43" style="line-height:10px;text-align: center" colspan="2" ></td>
                </tr>
               
                </table>
                 <tr align="left" border="0">
			<td colspan="5" width="100%" border="0"></td>
		</tr>
		 <tr align="left" border="0">
			<td colspan="5" width="100%" border="0"></td>
		</tr>
                 <tr align="left" border="0">
			<td colspan="5" width="100%" border="0">注：1.申请者须仔细阅读相关专业转入要求，本表学生基本信息均为系统生成，手写无效。转入专业及班级由教务处审核后填写，考生填写无效。</td>
		</tr>
		<tr align="left">
			<td colspan="5" width="100%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.若拟转专业1不符合专业要求，学校将按拟转专业2进行专业调整，若还不符合，则仍在原专业就读，此表失效。
</td>
		</tr>
		<tr align="left">
			<td colspan="5" width="100%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.参加中欧选拔，且已确认转入中欧学院者，此表失效。 </td>
		</tr>
						</td>
                    </tr>
EOF;
        $html_cont .= $html_str;

        $html_footer = <<<EOF
       
			</tbody>
		</table>
		
		
		
EOF;
        $html = $html_header.$html_cont.$html_footer;
        //dump($html);die;
        $pdf->writeHTML($html, true, false, true, false, '');
        $pdf->Output('本科新生转专业申请表'.".pdf", 'D');
    }

    /**
     * @desc arraySort php二维数组排序 按照指定的key 对数组进行排序
     * @param array $arr 将要排序的数组
     * @param string $keys 指定排序的key
     * @param string $type 排序类型 asc | desc
     * @return array
     */
    public function arraySort($arr, $keys, $type = 'asc') {
        $keysvalue = $new_array = array();
        foreach ($arr as $k => $v){
            $keysvalue[$k] = $v[$keys];
        }
        $type == 'asc' ? asort($keysvalue) : arsort($keysvalue);
        reset($keysvalue);
        foreach ($keysvalue as $k => $v) {
            $new_array[$k] = $arr[$k];
        }
        return $new_array;
    }


    /**
     * 根据HTML代码获取word文档内容
     * 创建一个本质为mht的文档，该函数会分析文件内容并从远程下载页面中的图片资源
     * 该函数依赖于类MhtFileMaker
     * 该函数会分析img标签，提取src的属性值。但是，src的属性值必须被引号包围，否则不能提取
     *
     * @param string $content HTML内容
     * @param string $absolutePath 网页的绝对路径。src路径为相对路径，那么就需要填写这个参数，来让该函数自动填补成绝对路径。这个参数最后需要以/结束
     * @param bool $isEraseLink 是否去掉HTML内容中的链接
     */
    public function getWordDocument( $content , $absolutePath = "" , $isEraseLink = true)
    {
        $mht = new \Think\MhtFileMaker();
        if ($isEraseLink)
            $content = preg_replace('/<a\s*.*?\s*>(\s*.*?\s*)<\/a>/i' , '$1' , $content);   //去掉链接

        $images = array();
        $files = array();
        $matches = array();
        //这个算法要求src后的属性值必须使用引号括起来  bak:/<img[.\n]*?src\s*?=\s*?[\"\'](.*?)[\"\'](.*?)\/>/i
        if ( preg_match_all('/<img.*?src="(.*?)".*?>/is',$content ,$matches ) )
        {
            $arrPath = $matches[1];
            for ( $i=0;$i<count($arrPath);$i++)
            {
                $path = $arrPath[$i];
                $imgPath = trim( $path );
                if ( $imgPath != "" )
                {
                    $files[] = $imgPath;
                    if( substr($imgPath,0,7) == 'http://')
                    {
                        //绝对链接，不加前缀
                    }
                    else
                    {
                        $imgPath = $absolutePath.$imgPath;
                    }
                    $images[] = $imgPath;
                }
            }
        }

        $mht->AddContents("tmp.html",$mht->GetMimeType("tmp.html"),$content);

        for ( $i=0;$i<count($images);$i++)
        {
            $image = $images[$i];
            if ( @fopen($image , 'r') )
            {
                $imgcontent = @file_get_contents( $image );
                if ( $content )
                    $mht->AddContents($files[$i],$mht->GetMimeType($image),$imgcontent);
            }
            else
            {
                echo "file:".$image." not exist!<br />";
            }
        }
        return $mht->GetFile();
    }
}