<?php
namespace Home\Model;
use Think\Model;
class GspydybmModel extends Model
{
    protected $_validate = array(
        array('xm', 'require', '姓名必填', 1, '', 3),
        array('xb', 'require', '性别必填', 1, '', 3),
        array('csny', 'require', '出生年月必填', 1, '', 3),
        array('csny', '/^\d{4}-\d{2}-\d{2}$/', '出生年月格式错误', 1, 'regex', 3),
        array('age', 'require', '年龄必填', 1, '', 3),
        array('age', '/^\d{2}$/', '年龄错误', 1, 'regex', 3),
        array('mz', 'require', '民族必填', 1, '', 3),
        array('sfzh', 'require', '身份证号码必填', 1, '', 3),
        array('sfzh', '', '身份证号码已经存在', 1, 'unique', 1),
        array('sfzh', 'isCreditNo', '身份证号码不合法', 1, 'function', 3),
        array('zzmm', 'require', '政治面貌必填', 1, '', 3),
        array('hjszd', 'require', '高考所在地必选', 1, '', 3),
//        array('lxdh', 'require', '联系电话必填', 1, '', 3),
        array('bkxm_id', 'require', '报考项目必填', 1, '', 3),
        array('wz', 'require', '位置（级别）必填', 1, '', 3),
        array('yddj', 'require', '运动等级必填', 1, '', 3),
        //array('zsbh', 'require', '证书编号必填', 1, '', 3),
        array('sg', 'require', '身高必填', 1, '', 3),
        array('tz', 'require', '体重必填', 1, '', 3),
//        array('fx', 'require', '副项必填', 1, '', 3),
        array('zp', 'require', '照片必填', 1, '', 3),
        array('zp', 'isFileExistence', '照片不存在', 1, 'function', 3),
        array('txdz', 'require', '通讯地址必填', 1, '', 3),
        array('yzbm', 'require', '邮政编码必填', 1, '', 3),
        array('byyx', 'require', '毕业院校必填', 1, '', 3),
        array('gklb', 'require', '高考类别必选', 1, '', 3),
        //array('gkkh', 'require', '高考考号必填', 1, '', 3),
        array('shgx', 'require', '社会关系必填', 1, '', 3),
        array('grjl', 'require', '个人简历必填', 1, '', 3),
        array('ydcj', 'require', '运动成绩必填', 1, '', 3),
        //array('gkbmcl', 'require', '高考报名确认单或高考报名成功的网络截图必传', 1, '', 3),
        //array('ksbrsfz1', 'require', '考生本人身份证真面必传', 1, '', 3),
        //array('ksbrsfz2', 'require', '考生本人身份证反面必传', 1, '', 3),
        //array('hkbzy', 'require', '户口本户主页必传', 1, '', 3),
        //array('hkbgry', 'require', '户口本户本人页必传', 1, '', 3),
        //array('byzs', 'require', '高中毕业证书或同等学历证书必传', 1, '', 3),
        array('ydyzs', 'require', '运动员二级以上（含二级）证书必传', 1, '', 3),
        array('ydydjxxjt', 'require', '运动等级详细信息截图必传', 1, '', 3),
        //array('bshjzs', 'require', '高中阶段参加省级以上比赛的获奖证书必传', 1, '', 3),
        //array('cxcfm', 'require', '秩序册封面必传', 1, '', 3),
        //array('cxcbry', 'require', 'c必传', 1, '', 3),
        //array('cjcfm', 'require', '成绩册封面必传', 1, '', 3),
        //array('cjcbry', 'require', '成绩册本人页必传', 1, '', 3),
        //array('gkbmcl', 'isFileExistence', '高考报名确认单或高考报名成功的网络截图不存在', 1, 'function', 3),
        //array('ksbrsfz1', 'isFileExistence', '考生本人身份证真面不存在', 1, 'function', 3),
        //array('ksbrsfz2', 'isFileExistence', '考生本人身份证反面不存在', 1, 'function', 3),
        //array('hkbzy', 'isFileExistence', '户口本户主页不存在', 1, 'function', 3),
        //array('hkbgry', 'isFileExistence', '户口本户本人页不存在', 1, 'function', 3),
        //array('byzs', 'isFileExistence', '高中毕业证书或同等学历证书不存在', 1, 'function', 3),
        array('ydyzs', 'isFileExistence', '运动员二级以上（含二级）证书不存在', 1, 'function', 3),
        array('ydydjxxjt', 'isFileExistence', '运动等级详细信息截图不存在', 1, 'function', 3),
        //array('bshjzs', 'isFileExistence', '高中阶段参加省级以上比赛的获奖证书不存在', 1, 'function', 3),
        //array('cxcfm', 'isFileExistence', '秩序册封面不存在', 1, 'function', 3),
        //array('cxcbry', 'isFileExistence', '秩序册本人页不存在', 1, 'function', 3),
        //array('cjcfm', 'isFileExistence', '成绩册封面不存在', 1, 'function', 3),
        //array('cjcbry', 'isFileExistence', '成绩册本人页不存在', 1, 'function', 3),
    );
//    protected $_auto = array(
//    );
}